# Case study 10 - Probability

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv('mushrooms.csv')

In [3]:
data.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [4]:
data.shape

(8124, 23)

In [5]:
data.isnull().any()

class                       False
cap-shape                   False
cap-surface                 False
cap-color                   False
bruises                     False
odor                        False
gill-attachment             False
gill-spacing                False
gill-size                   False
gill-color                  False
stalk-shape                 False
stalk-root                  False
stalk-surface-above-ring    False
stalk-surface-below-ring    False
stalk-color-above-ring      False
stalk-color-below-ring      False
veil-type                   False
veil-color                  False
ring-number                 False
ring-type                   False
spore-print-color           False
population                  False
habitat                     False
dtype: bool

There are no null values in the dataset

In [6]:
data.describe()

class cap-shape cap-surface cap-color bruises  odor gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
count          8124      8124       8124  ...                     8124   
unique            2         2         12  ...                        4   
top               c         b          b  ...                        s   
freq           6812      5612       1728  ...                     4936   

       stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       ring-number ring-type spore-print-color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder
label_en=LabelEncoder()
data=data.apply(label_en.fit_transform)
data.head()

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [8]:
data.columns

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

In [9]:
x=data.drop(['class','veil-type'],axis=1)
y=data['class']

In [10]:
#Splitting the dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.3)

# ML

In [11]:
from sklearn.linear_model import LogisticRegression
logit_model=LogisticRegression()
logit_model.fit(x_train,y_train)
y_pred=logit_model.predict(x_test)

C:\Users\stbch\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

In [13]:
print('accuracy is :',accuracy_score(y_test,y_pred))
print('precision is :',precision_score(y_test,y_pred,average='micro'))
print('recall is :',recall_score(y_test,y_pred,average='micro'))
print('f1 is :',f1_score(y_test,y_pred,average='micro'))

accuracy is : 0.9499589827727646
precision is : 0.9499589827727646
recall is : 0.9499589827727646
f1 is : 0.9499589827727646


In [14]:
confusion_matrix(y_test,y_pred)

array([[1200,   57],
       [  65, 1116]], dtype=int64)

In [15]:
from sklearn.tree import DecisionTreeClassifier
dt_model=DecisionTreeClassifier()
dt_model.fit(x_train,y_train)
y_pred=dt_model.predict(x_test)
print('Accuracy on Decision tree model is :',accuracy_score(y_test,y_pred))

Accuracy on Decision tree model is : 1.0


In [17]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
f1_score(y_test,y_pred)

1.0

In [18]:
confusion_matrix(y_test,y_pred)

array([[1257,    0],
       [   0, 1181]], dtype=int64)

In [19]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train, y_train)
y_pred=nb.predict(x_test)

In [20]:
accuracy_score(y_test,y_pred)

0.9294503691550451

In [21]:
confusion_matrix(y_test,y_pred)

array([[1172,   85],
       [  87, 1094]], dtype=int64)

In [22]:
from sklearn.naive_bayes import BernoulliNB
bnb= BernoulliNB()
bnb.fit(x_train,y_train)
y_pred=bnb.predict(x_test)

In [23]:
accuracy_score(y_test,y_pred)

0.8461853978671042

In [24]:
confusion_matrix(y_test,y_pred)

array([[1193,   64],
       [ 311,  870]], dtype=int64)

In [26]:
from sklearn.metrics import classification_report

In [27]:
print("Naive Bayes Classifier report: \n\n", classification_report(y_test, y_pred))

Naive Bayes Classifier report: 

               precision    recall  f1-score   support

           0       0.79      0.95      0.86      1257
           1       0.93      0.74      0.82      1181

    accuracy                           0.85      2438
   macro avg       0.86      0.84      0.84      2438
weighted avg       0.86      0.85      0.84      2438



In [28]:
print("Bernoulli Classifier report: \n\n", classification_report(y_test, y_pred))

Bernoulli Classifier report: 

               precision    recall  f1-score   support

           0       0.79      0.95      0.86      1257
           1       0.93      0.74      0.82      1181

    accuracy                           0.85      2438
   macro avg       0.86      0.84      0.84      2438
weighted avg       0.86      0.85      0.84      2438

